# Generated by Django 5.2.4 on 2025-07-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('AÇÃO', 'Ação'), ('COMÉDIA', 'Comédia'), ('DRAMA', 'Drama'), ('TERROR', 'Terror'), ('ROMANCE', 'Romance'), ('FICÇÃO', 'Ficção Científica'), ('ANIMAÇÃO', 'Animação')], max_length=20)),
                ('mes_assistido', models.CharField(max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
