# Generated by Django 5.2.4 on 2025-07-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='cartaz_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
