# Generated by Django 5.2.4 on 2025-07-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_filme_cartaz_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='cartaz_url',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='data_cadastro',
        ),
        migrations.AddField(
            model_name='filme',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='genero',
            field=models.CharField(max_length=50),
        ),
    ]
